<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Admission;

class AdmissionSeeder extends Seeder
{
    public function run()
    {
        Admission::insert([
            [
                'token' => '928n1lHm8J7Ffl',
                'student_id' => '1',
                'name_bangla' => 'Grant Cantu',
                'name_english' => 'Blake Snider',
                'birth_certificate_number' => '814',
                'birth_date' => '29-Jan-2003',
                'gender' => 'women',
                'father_bangla' => 'Hakeem Moses',
                'father_english' => 'Cameron Vasquez',
                'father_nid' => '290',
                'father_birth_date' => '26-Jun-2007',
                'father_mobile' => '01892311511',
                'mother_bangla' => 'Nehru Richards',
                'mother_english' => 'Maggie David',
                'mother_nid' => '148',
                'mother_birth_date' => '05-Oct-2015',
                'mother_mobile' => '445',
                'permanent_division' => 'Sylhet',
                'permanent_zilla' => 'Sylhet',
                'permanent_thana' => 'Kanaighat',
                'permanent_union' => 'Digirpar Purbo',
                'permanent_post' => 'Suscipit ut harum no',
                'permanent_address' => 'Ut lorem impedit la',
                'current_division' => 'Dhaka',
                'current_zilla' => 'Madaripur',
                'current_thana' => 'Kalkini',
                'current_union' => 'Ramjanpur',
                'current_post' => 'Aut qui consequatur ',
                'current_address' => 'Qui quia rerum tempo',
                'previous_division' => 'Rajshahi',
                'previous_zilla' => 'Bogura',
                'previous_thana' => 'Sherpur',
                'previous_institute' => 'Grady Sargent',
                'previous_board' => 'Autem eveniet corpo',
                'previous_result_type' => 'cgpa',
                'previous_passing_year' => '2005',
                'previous_technology' => 'Quia eu deserunt ull',
                'previous_exam' => 'Maite Noble',
                'previous_registration' => '895',
                'previous_roll' => 'Quod amet modi exer',
                'previous_result' => 'Sunt animi repellen',
                'guardian_relation' => 'brother',
                'guardian_bangla' => 'Davis Meyer',
                'guardian_english' => 'Karen Mcclain',
                'guardian_mobile' => '781',
                'guardian_nid' => '998',
                'guardian_birth_date' => '31-Oct-1970',
                'student_relation' => 'guardian',
                'ethnic_child' => 'yes',
                'freedom_family' => 'no',
                'stipend' => 'yes',
                'disability' => 'no',
                'photo' => '/public/resource/images/c68658b8fdf6770207b4cd72319de88d.png',
                'documents' => '/public/resource/images/34a4c4cf176b90ea8d92b79a833a8fec.jpg',
                'status' => 'approved',
                'is_paid' => '0',
                'payment_id' => null,
                'created_at' => '2023-11-23 19:31:08',
            ],
            [
                'token' => '09J6FGk5vIMEAJ_1676332561',
                'student_id' => '2',
                'name_bangla' => 'শিক্ষার্থীর নাম',
                'name_english' => 'শিক্ষার্থীর নাম',
                'birth_certificate_number' => '295',
                'birth_date' => '20-Sep-2016',
                'gender' => 'women',
                'father_bangla' => 'পিতার নাম',
                'father_english' => 'Eos officia nesciun',
                'father_nid' => 'In voluptatem Tempo',
                'father_birth_date' => '20-Aug-2020',
                'father_mobile' => '01892311511',
                'mother_bangla' => 'মাতার নাম ',
                'mother_english' => 'Omnis consequatur E',
                'mother_nid' => 'Ab sunt in lorem ni',
                'mother_birth_date' => '18-Sep-2018',
                'mother_mobile' => 'Velit temporibus qui',
                'permanent_division' => 'খুলনা',
                'permanent_zilla' => 'খুলনা',
                'permanent_thana' => 'তেরখাদা',
                'permanent_union' => 'সাচিয়াদাহ',
                'permanent_post' => 'Et commodi ut eos a',
                'permanent_address' => 'Quidem non vel saepe',
                'current_division' => 'রংপুর',
                'current_zilla' => 'রংপুর',
                'current_thana' => 'মিঠাপুকুর',
                'current_union' => 'চেংমারী',
                'current_post' => 'Eum omnis est occae',
                'current_address' => 'Ducimus et omnis nu',
                'previous_division' => 'চট্টগ্রাম',
                'previous_zilla' => 'লক্ষ্মীপুর',
                'previous_thana' => 'কমলনগর',
                'previous_institute' => 'Beatae eum animi ve',
                'previous_board' => 'Reprehenderit minim ',
                'previous_result_type' => 'cgpa',
                'previous_passing_year' => '1974',
                'previous_technology' => 'Quis laboris eiusmod',
                'previous_exam' => 'Soluta minima doloru',
                'previous_registration' => 'Dolores nulla quisqu',
                'previous_roll' => 'Occaecat sint ipsa ',
                'previous_result' => 'Non repudiandae volu',
                'guardian_relation' => 'others',
                'guardian_bangla' => 'Laboriosam quae off',
                'guardian_english' => 'Quibusdam ex est ull',
                'guardian_mobile' => 'Saepe vel ut ex at i',
                'guardian_nid' => 'Et mollit voluptatib',
                'guardian_birth_date' => '20-Jul-1979',
                'student_relation' => 'mother',
                'ethnic_child' => 'yes',
                'freedom_family' => 'yes',
                'stipend' => 'yes',
                'disability' => 'yes',
                'photo' => '/public/resource/images/bee5f6b7d06ea92bb5fbf05633ec440c.png',
                'documents' => '/public/resource/images/3ebbb3d1ee664b2ff098b7f6aa181d87.png',
                'status' => 'pending',
                'is_paid' => '0',
                'payment_id' => null,
                'created_at' => '2023-11-23 19:35:52',
            ],
        ]);
    }
}
