<?php

// project constant variables
const ICONS = [
    'home' => '<iconify-icon icon="flowbite:home-solid" width="24" height="24"></iconify-icon>',
    'dashboard' => '<iconify-icon icon="ri:dashboard-fill" width="24" height="24"></iconify-icon>',
    'academic' => '<iconify-icon icon="heroicons-solid:academic-cap" width="24" height="24"></iconify-icon>',
    'administration' => '<iconify-icon icon="medical-icon:i-administration" width="24" height="24"></iconify-icon>',
    'finance' => '<iconify-icon icon="material-symbols:finance-rounded" width="24" height="24"></iconify-icon>',
    'communication' => '<iconify-icon icon="ix:communication-filled" width="24" height="24"></iconify-icon>',
    'reports' => '<iconify-icon icon="iconoir:reports-solid" width="24" height="24"></iconify-icon>',
    'information' => '<iconify-icon icon="streamline-flex:information-circle-solid" width="24" height="24"></iconify-icon>',
    'settings' => '<iconify-icon icon="solar:settings-bold" width="24" height="24"></iconify-icon>',
    'media' => '<iconify-icon icon="ic:outline-perm-media" width="24" height="24"></iconify-icon>',
    'public' => '<iconify-icon icon="octicon:feed-public-16" width="24" height="24"></iconify-icon>',
    'menu.add' => '<iconify-icon icon="material-symbols:page-menu-ios-rounded" width="24" height="24"></iconify-icon>',
    'page' => '<iconify-icon icon="streamline-ultimate:book-book-pages-bold" width="24" height="24"></iconify-icon>',
    'right_arrow' => '<iconify-icon icon="line-md:arrow-right" width="14" height="14"></iconify-icon>',
    'edit' => '<iconify-icon icon="basil:edit-outline" width="24" height="24"></iconify-icon>',
    'admission.request' => '<iconify-icon icon="entypo:add-user" width="24" height="24"></iconify-icon>',
    'delete' => '<iconify-icon icon="fluent:delete-20-regular" width="24" height="24"></iconify-icon>',
    'save' => '<iconify-icon icon="line-md:check-all" width="24" height="24"></iconify-icon>',
    'print' => '<iconify-icon icon="noto:printer" width="24" height="24"></iconify-icon>',
    'view' => '<iconify-icon icon="emojione-monotone:eye" width="24" height="24"></iconify-icon>',
    'reject' => '<iconify-icon icon="mage:file-minus" width="24" height="24"></iconify-icon>',
    'approve' => '<iconify-icon icon="mdi:approve" width="24" height="24"></iconify-icon>',
    'send' => '<iconify-icon icon="streamline:send-email-remix" width="24" height="24"></iconify-icon>',
    'facebook' => '<iconify-icon icon="streamline-flex:facebook-1-solid" width="24" height="24"></iconify-icon>',
    'twitter' => '<iconify-icon icon="entypo-social:twitter-with-circle" width="24" height="24"></iconify-icon>',
    'instagram' => '<iconify-icon icon="f7:logo-instagram" width="24" height="24"></iconify-icon>',
    'linkedin' => '<iconify-icon icon="entypo-social:linkedin-with-circle" width="24" height="24"></iconify-icon>',
    'reddit' => '<iconify-icon icon="ant-design:reddit-circle-filled" width="24" height="24"></iconify-icon>',
    'x' => '<iconify-icon icon="streamline-logos:x-twitter-logo-block" width="24" height="24"></iconify-icon>',
    'tiktok' => '<iconify-icon icon="mage:tiktok-circle" width="24" height="24"></iconify-icon>'
];
